// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbvclewgtpjmikdqphmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhidmNsZXdndHBqbWlrZHFwaG1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MjQzMTYsImV4cCI6MjA3NDUwMDMxNn0.U_1AAdZalJNUEunH0f1RTV0W4RGlKV4jUnAPaedY3fc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});